/// Flutter icons BotIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BotIcon
///      fonts:
///       - asset: fonts/BotIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BotIcon {
  BotIcon._();

  static const _kFontFam = 'BotIcon';
  static const String? _kFontPkg = null;

  static const IconData bot_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
