/// Flutter icons LanguageIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LanguageIcons
///      fonts:
///       - asset: fonts/LanguageIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LanguageIcons {
  LanguageIcons._();

  static const _kFontFam = 'LanguageIcons';
  static const String? _kFontPkg = null;

  static const IconData engIcon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sinIcon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
